# action.yml
name: 'OpenAPI Diff GH action'
description: 'Runs openapitools/openapi-diff and provides results in step outputs'
inputs:
  new-openapi-spec:
    description: 'Absolute path to changed OpenAPI spec'
    required: true
  current-openapi-spec:
    description: 'Absolute path to the current OpenAPI spec'
    required: true
  only-state:
    description: 'Only output diff state: no_changes, incompatible, compatible'
    required: false
    default: 'true'
outputs:
  openapi-diff-state:
    description: 'Result of the diff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.new-openapi-spec }}
    - ${{ inputs.current-openapi-spec }}
    - ${{ inputs.only-state }}