# action.yml
name: 'OpenAPI Diff GH action'
description: 'Runs openapitools/openapi-diff and provides results in step outputs'
inputs:
  service-name:
    description: 'Name of the service that owns the OpenAPI spec'
    required: true
  new-openapi-spec:
    description: 'Absolute path to changed OpenAPI spec'
    required: true
  current-openapi-spec:
    description: 'Absolute path to the current OpenAPI spec'
    required: true
outputs:
  openapi-diff-state:
    description: 'Result of the diff: no_changed, incompatible, compatible'
  openapi-html-result:
    description: 'HTML file containing the detailed results of the diff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service-name }}
    - ${{ inputs.new-openapi-spec }}
    - ${{ inputs.current-openapi-spec }}